### ISSUE TITLE
basic example out of date?

### ISSUE THREAD

**Issue by ITwrx** [guzba/ready#1]
the [basic example](https://github.com/guzba/ready/blob/master/examples/basic.nim)

returns: `Error: attempting to call undeclared routine: 'roundtrip'`

p.s. you might consider adding the `redis.close()` to at least one of the `readme` examples (it's mentioned in the text, but not included in any example), as well as the `compile command` ready expects people to use, just for clarity, completeness, and convenience. 

thanks

**Comment by guzba** [comment]
Thanks for the note about the examples, I've updated them (https://github.com/guzba/ready/commit/4fdf3e779dc0f2c7510f48a145b9107dc0362e7a).

As for showing `close`, I have it there but tbh I am not aware of any scenarios where closing a Redis connection is a good idea. I think it would be worse to make it seem like the idea of closing a connection is a good thing one may do.

**Comment by ITwrx** [comment]
well, i'm confused. This is the first time i'm using redis without some convenience layer like laravel's cache feature, so i'm just trying to follow the ready docs and reading up on redis from their docs. Right now actually, because i'm trying to implement cookie auth with redis session backend for my mummy SSR monolith project.

the ready docs say:
`Remember to call close if you no longer need a Redis connection. The connections are not garbage collected.`

the above is why i was suggesting that `close()` be shown.

now you say: 
` I am not aware of any scenarios where closing a Redis connection is a good idea. I think it would be worse to make it seem like the idea of closing a connection is a good thing one may do.`

As a lower level redis beginner, now, i'm not sure when, or if, i should close a connection. A production-usable example (for me and others who have never used redis directly) would demonstrate this, especially since it's going to cause a mem leak if done incorrectly, by the sound of it.

thanks

**Comment by guzba** [comment]
If you're working in the context of a Mummy server, I would suggest the following (I should make an example for this too, always more examples to make! haha)

First, use a pool. Something like:

`let pool = newRedisPool(4)`

The number (4 in this case) is the number of Redis connections to open in the pool. Each one can handle an incredible number of commands per second so you will need only a couple (2-4 for many 10s of thousands of requests per second to a same region / local Redis server)

then use `pool.command` basically all the time. It takes care of waiting for an available conn, using it, then returning it to the pool. There are other options but this covers 90%+ of scenarios I would say.

This Redis pool should be a global and never closed. It lives as long as the server process lives.

If you are concerned the connections could be close for any reason, you can add a borrow callback as show in this example to detect that and recover: https://github.com/guzba/ready/blob/master/examples/pool_borrow_callback.nim

I have tried to explain how to use Ready, but also explaining Redis at the same time is a lot to do in one readme file. I hope this helps explain a bit better how to get up and running.

**Comment by guzba** [comment]
Here is a quick example of how I suggest using Mummy and Ready together: https://github.com/guzba/ready/blob/master/examples/mummy_server.nim

**Comment by ITwrx** [comment]
thanks a lot. that's what i needed to know, and the above is a good, clear explanation. i'll just use a pool. 

You might consider updating the readme to recommend using a pool IRT this connection-closing issue, as opposed to just performance. I thought since i was in early stages of dev and/or minimal usage (no current performance concerns) i didn't need to bother with pools, but i think i would have if i knew it solved the close() issue too.

**Comment by guzba** [comment]
This is great feedback, I'll make some improvements.

**Comment by ITwrx** [comment]
thanks for the example too!
