### ISSUE TITLE
how to use ready with hmset and multiple values?

### ISSUE THREAD

**Issue by greenersharp** [guzba/ready#14]
Let's say I have a simple Table[string,string]

The table can have many entries, but in this example it only has two.

`let example_table = {"name":"john","age":"333"}.totable`

Now, I want to store this Table into a redis Hash, using HMSET

How can I accomplish this with Ready?

this simple attempt fails.  
```
let pool = newRedisConn() 
echo pool.command("hmset", "test_key", example_table)

```

I also tried `example_table.toseq` but that failed too.

Can you provide an example of of how i can achieve this with Ready?

Thank you

**Comment by guzba** [comment]
Ready generally is used exactly like the Redis command would be from the command line. In this case `HMSET key field value [field value ...]`

Would be:

```nim
pool.command("HMSET", "key", "field", "value", "field2", "value2", ...)
```

From your table example:

```nim
pool.command("hmset", "test_key", "name", "john", "age", "333")
```

A helper proc could be made to unwrap a table into a seq of strings, which could then be used with `send` followed by `receive`:

```nim
var myseq = @[...] # Convert table to seq for sending to Redis
discard pool.send([
  ("HMSET", myseq)
])
result = pool.receive()
```

**Comment by greenersharp** [comment]
Thank you for the response but I am still getting an error when trying your suggestion.

```
import ready, tables

let pool = newRedisConn()

proc table_to_seq(redis_key:string,table:auto): seq[string] = 
    var output = @[redis_key]
    for k in table.pairs:
        output.add k[0]
        output.add k[1]
    return output

var t = {"name":"john","age":"333"}.toTable

var myseq = table_to_seq("test_key",t)
echo myseq #  @["test_key", "name", "john", "age", "333"]
echo myseq.type #  seq[string]

discard pool.send([("HMSET", myseq)])
result = pool.receive()
```
The code generates this error on the `pool.send` line:
Error: expression 'send(pool, [("HMSET", myseq)])' has no type (or is ambiguous)

**Comment by guzba** [comment]
I forgot that send and receive are on a connection, not the pool, so you'll need to claim a connection for a block to do the work:

```nim
pool.withConnection conn:
  conn.send([("HMSET", myseq)])
  result = conn.receive()
```
